name: Build CI

on:
  workflow_dispatch:
  
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    
    - name: Install Dependencies
      run: |
          sudo apt-get update && sudo apt-get -y upgrade
          sudo apt-get -y install git make gcc bc bison flex libssl-dev ccache libelf-dev libncurses-dev
          sudo apt-get -y install bc \
            binutils-dev \
            bison \
            build-essential \
            ca-certificates \
            ccache \
            clang \
            cmake \
            curl \
            file \
            flex \
            git \
            libelf-dev \
            libssl-dev \
            lld \
            make \
            ninja-build \
            python3-dev \
            texinfo \
            u-boot-tools \
            xz-utils \
            zlib1g-dev

    - name: Set up JDK
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        java-package: 'jdk'
        architecture: 'x64'
        check-latest: false
        server-id: 'github'
        server-username: ${{ github.actor }}
        server-password: ${{ secrets.GITHUB_TOKEN }}
        overwrite-settings: true
        job-status: 'success' 
        distribution: 'adopt'

    - name: Build with Gradle
      run: ./gradlew build --warning-mode all

    - name: Run tests
      run: ./gradlew test
