name: Build and Test

on:
  workflow_dispatch:
  
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up JDK
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        java-package: 'jdk'
        architecture: 'x64'
        check-latest: false
        server-id: 'github'
        server-username: ${{ github.actor }}
        server-password: ${{ secrets.GITHUB_TOKEN }}
        overwrite-settings: true
        job-status: 'success'

    - name: Build with Gradle
      run: ./gradlew build

    - name: Run tests
      run: ./gradlew test
