name: Build CI

on:
  workflow_dispatch:
  
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Set up CMake 
      uses: cmake/action-setup@v2
      with:
        cmake-version: '3.21'

    - name: Set up JDK
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        java-package: 'jdk'
        architecture: 'x64'
        check-latest: false
        server-id: 'github'
        server-username: ${{ github.actor }}
        server-password: ${{ secrets.GITHUB_TOKEN }}
        overwrite-settings: true
        job-status: 'success' 
        distribution: 'adopt'

    - name: Build with Gradle
      run: ./gradlew build --warning-mode all

    - name: Run tests
      run: ./gradlew test
